---
- name: Create application environment file
  template:
    src: .env.j2
    dest: "{{ app_directory }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0600'
  tags: [application]

- name: Create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_directory }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
  tags: [application]

- name: Create systemd service for application
  template:
    src: spree-staging.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  notify:
    - reload systemd
    - restart application
  tags: [application]

- name: Enable application service
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    daemon_reload: yes
  tags: [application]
