---
- name: Create application user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    home: "/home/{{ app_user }}"
    create_home: yes
    groups: docker,sudo
    append: yes
  tags: [user]

- name: Set up SSH directory for app user
  file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0700'
  tags: [user]

- name: Copy SSH authorized keys
  copy:
    src: /root/.ssh/authorized_keys
    dest: "/home/{{ app_user }}/.ssh/authorized_keys"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0600'
    remote_src: yes
  tags: [user]

- name: Create application directory
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  tags: [user]

- name: Create storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ app_directory }}/storage"
    - "{{ app_directory }}/storage/databases"
    - "{{ app_directory }}/logs"
    - "{{ backup_location }}"
  tags: [user]

- name: Allow app user sudo without password for docker
  lineinfile:
    path: /etc/sudoers.d/{{ app_user }}
    line: "{{ app_user }} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/local/bin/docker-compose"
    create: yes
    validate: 'visudo -cf %s'
  tags: [user]
