# Encrypted with: ansible-vault encrypt vault/secrets.yml
# This file should contain:
# vault_rails_master_key: your_rails_master_key_here
# vault_registry_password: your_docker_registry_password_here

# Example (replace with your actual values):
vault_rails_master_key: your_rails_master_key_from_config_master_key
vault_registry_password: your_dockerhub_password
