---
- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags: [system]

- name: Set locale
  locale_gen:
    name: "{{ locale }}"
    state: present
  tags: [system]

- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  tags: [system]

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - build-essential
      - python3-pip
    state: present
  tags: [system]

- name: Install SQLite
  apt:
    name:
      - sqlite3
      - libsqlite3-dev
    state: present
  tags: [system, database]

- name: Create swap file (if not exists)
  block:
    - name: Check if swap exists
      stat:
        path: /swapfile
      register: swap_file

    - name: Create swap file
      command: fallocate -l 2G /swapfile
      when: not swap_file.stat.exists

    - name: Set swap permissions
      file:
        path: /swapfile
        mode: '0600'
      when: not swap_file.stat.exists

    - name: Make swap
      command: mkswap /swapfile
      when: not swap_file.stat.exists

    - name: Enable swap
      command: swapon /swapfile
      when: not swap_file.stat.exists

    - name: Add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present
      when: not swap_file.stat.exists
  tags: [system, swap]
