# config/deploy.yml
service: spree-rails8-staging
image: viandrianoff/spree-rails8-staging

# ARM64 architecture for Hetzner ARM server
builder:
  arch: arm64
  secrets:
   - RAILS_MASTER_KEY
# Deploy to our staging server with deploy user
# SSH configuration
ssh:
  user: deploy

# Правильная структура servers
servers:
  web:
    hosts:  
      - 95.217.223.50
    options:
      memory: 1g
  job:
    hosts:
      - 95.217.223.50
    cmd: bin/jobs


# SSL is handled by Nginx (configured by Ansible)
proxy:
  ssl: true
  forward_headers: true
  host: staging.andrianoff.online
  app_port: 3000


# Registry configuration
registry:
  username: viandrianoff
  password:
    - KAMAL_REGISTRY_PASSWORD

# Environment variables
env:
  clear:
    RAILS_ENV: staging
    PORT: 3000
    DATABASE_URL: sqlite3:/rails/storage/databases/staging.sqlite3
    SOLID_QUEUE_IN_PUMA: true
    JOB_CONCURRENCY: 2
    WEB_CONCURRENCY: 2
    RAILS_LOG_LEVEL: debug

  secret:
    - RAILS_MASTER_KEY

# Docker managed volume for persistent storage
volumes:
  - "spree_staging_storage:/rails/storage"

# Команды после деплоя
boot:
  limit: 10
  wait: 2

# Увеличиваем timeout для Rails + Spree запуска
deploy:
  timeout: 60s




