---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: [nginx]

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags: [nginx]

- name: Create Nginx configuration for staging
  template:
    src: staging.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    backup: yes
  notify: restart nginx
  tags: [nginx]

- name: Enable Nginx site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link
  notify: restart nginx
  tags: [nginx]

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: [nginx]
