---
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart application
  systemd:
    name: "{{ app_name }}"
    state: restarted
